server:
  port: 8080
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    basedir: ./temp

spring:
  application:
    name: literature-assistant
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    throw-exception-if-no-handler-found: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

# Knife4j Configuration
knife4j:
  enable: true
  setting:
    language: zh_cn
    enable-swagger-models: true
    enable-document-manage: true

# MyBatis Plus Configuration
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.literature.assistant.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# File Upload Configuration
file:
  upload:
    path: ./uploads/
    max-size: 50MB
    allowed-extensions: .pdf,.doc,.docx,.md,.txt

# AI Service Configuration
ai:
  kimi:
    base-url: https://api.moonshot.cn/v1
    timeout: 30000
    max-tokens: 4096
    temperature: 0.7
    # 从环境变量 KIMI_API_KEY 读取，如果未设置则为空
    api-key: ${KIMI_API_KEY:}

logging:
  level:
    com.literature.assistant: DEBUG
    org.springframework.web: INFO
  file:
    name: ./logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"